version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/_static
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn portfolio_prj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/_static
      - ./:/usr/src/app/
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
volumes:
  static_volume: